import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sfPro = localFont({
  src: "./fonts/SFPRODISPLAYREGULAR.otf",
  variable: "--font-sf-pro",
  weight: "100 400",
});
const sfProBold = localFont({
  src: "./fonts/SFPRODISPLAYBOLD.otf",
  variable: "--font-sf-pro-bold",
  weight: "100 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sfPro.variable} ${sfProBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
